function cosmo = cosmo_init()
%--------------------------------------------------------------
% Initializes the cosmological paramters
%--------------------------------------------------------------

c = 299792.458;
H_0 = 69.6;
Omega_R = 0.0;
Omega_M = 0.286;
Omega_L = 0.714;
Omega_K = 1 - (Omega_R + Omega_M + Omega_L);

cosmo = struct(...
    'c', c, ...
    'H_0', H_0, ...
    'Omega_R', Omega_R, ...
    'Omega_M', Omega_M, ...
    'Omega_L', Omega_L, ...
    'Omega_K', Omega_K, ...
    't_Hubble', 9.78e9 / H_0, ...
    'D_Hubble', c / H_0');